version: '3.8'
services:
  etl_app:
    build: .
    volumes:
      - ./data:/app/data
    command: python /app/src/main.py

  test_app:
    build: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: pytest /app/tests
